<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Árboles de clasificación | Modelos Predictivos</title>
  <meta name="description" content="Libro de Modelos Predictivos" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Árboles de clasificación | Modelos Predictivos" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/cover.png" />
  <meta property="og:description" content="Libro de Modelos Predictivos" />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Árboles de clasificación | Modelos Predictivos" />
  
  <meta name="twitter:description" content="Libro de Modelos Predictivos" />
  <meta name="twitter:image" content="/images/cover.png" />

<meta name="author" content="Freddy Hernández" />


<meta name="date" content="2024-04-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="arb-de-regre.html"/>
<link rel="next" href="arb-distri.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos Predictivos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="arb-de-regre.html"><a href="arb-de-regre.html"><i class="fa fa-check"></i><b>1</b> Árboles de regresión</a>
<ul>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#árboles"><i class="fa fa-check"></i>Árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#árbol-de-decisión"><i class="fa fa-check"></i>Árbol de decisión</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#tipos-de-árboles"><i class="fa fa-check"></i>Tipos de árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#árbol-de-regresión"><i class="fa fa-check"></i>Árbol de regresión</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#paquetes-de-r-para-árboles"><i class="fa fa-check"></i>Paquetes de R para árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#paquete-rpart"><i class="fa fa-check"></i>Paquete <strong>rpart</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#paquete-tree"><i class="fa fa-check"></i>Paquete <strong>tree</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#ejemplo-con-el-paquete-rpart"><i class="fa fa-check"></i>Ejemplo con el paquete <strong>rpart</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#ejemplo-con-el-paquete-tree"><i class="fa fa-check"></i>Ejemplo con el paquete <strong>tree</strong></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html"><i class="fa fa-check"></i><b>2</b> Árboles de clasificación</a>
<ul>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#árboles-1"><i class="fa fa-check"></i>Árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#árbol-de-decisión-1"><i class="fa fa-check"></i>Árbol de decisión</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#tipos-de-árboles-1"><i class="fa fa-check"></i>Tipos de árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#árbol-de-clasificación"><i class="fa fa-check"></i>Árbol de clasificación</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#paquetes-de-r-para-construir-árboles"><i class="fa fa-check"></i>Paquetes de R para construir árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#ejemplo-con-rpart"><i class="fa fa-check"></i>Ejemplo con <strong>rpart</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#ejemplo-con-tree"><i class="fa fa-check"></i>Ejemplo con <strong>tree</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="arb-distri.html"><a href="arb-distri.html"><i class="fa fa-check"></i><b>3</b> Árboles de regresión distribucionales</a>
<ul>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#videos-útiles"><i class="fa fa-check"></i>Videos útiles</a></li>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#paquete-disttree"><i class="fa fa-check"></i>Paquete disttree</a></li>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="svm-reg.html"><a href="svm-reg.html"><i class="fa fa-check"></i><b>4</b> Support Vector Machines para regresión</a>
<ul>
<li class="chapter" data-level="" data-path="svm-reg.html"><a href="svm-reg.html#paquetes-de-r-para-svm"><i class="fa fa-check"></i>Paquetes de R para svm</a></li>
<li class="chapter" data-level="" data-path="svm-reg.html"><a href="svm-reg.html#ventajas"><i class="fa fa-check"></i>Ventajas</a></li>
<li class="chapter" data-level="" data-path="svm-reg.html"><a href="svm-reg.html#ejemplos"><i class="fa fa-check"></i>Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="svm-clas.html"><a href="svm-clas.html"><i class="fa fa-check"></i><b>5</b> Support Vector Machines para clasificación</a>
<ul>
<li class="chapter" data-level="" data-path="svm-clas.html"><a href="svm-clas.html#paquetes-de-r-para-svm-1"><i class="fa fa-check"></i>Paquetes de R para svm</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="adaboost.html"><a href="adaboost.html"><i class="fa fa-check"></i><b>6</b> AdaBoost</a>
<ul>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#explicación-sencilla-de-adaboost"><i class="fa fa-check"></i>Explicación sencilla de AdaBoost</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#explicación-detallada-de-adaboost"><i class="fa fa-check"></i>Explicación detallada de AdaBoost</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="gradboost.html"><a href="gradboost.html"><i class="fa fa-check"></i><b>7</b> Gradient Boost</a>
<ul>
<li class="chapter" data-level="" data-path="gradboost.html"><a href="gradboost.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="gradboost.html"><a href="gradboost.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="gradboost.html"><a href="gradboost.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rand_forests.html"><a href="rand_forests.html"><i class="fa fa-check"></i><b>8</b> Random Forest</a>
<ul>
<li class="chapter" data-level="" data-path="rand_forests.html"><a href="rand_forests.html#explicación-sencilla-de-random-forests"><i class="fa fa-check"></i>Explicación sencilla de Random Forests</a></li>
<li class="chapter" data-level="" data-path="rand_forests.html"><a href="rand_forests.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="rand_forests.html"><a href="rand_forests.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="rand_forests.html"><a href="rand_forests.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="rand_forests.html"><a href="rand_forests.html#random-forests-distribucionales"><i class="fa fa-check"></i>Random Forests distribucionales</a></li>
<li class="chapter" data-level="" data-path="rand_forests.html"><a href="rand_forests.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html"><i class="fa fa-check"></i><b>9</b> Regresión lineal versus árboles de regresión</a>
<ul>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#regresión-lineal"><i class="fa fa-check"></i>Regresión lineal</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#arboles-de-regresión"><i class="fa fa-check"></i>Arboles de regresión</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#ejemplo-14"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#estudio-de-simulación-para-comparar-ambos-métodos"><i class="fa fa-check"></i>Estudio de simulación para comparar ambos métodos</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#retos"><i class="fa fa-check"></i>Retos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos Predictivos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="arb-de-clasif" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Árboles de clasificación<a href="arb-de-clasif.html#arb-de-clasif" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Los árboles de regresión/clasificación fueron propuestos por <a href="https://en.wikipedia.org/wiki/Leo_Breiman">Leo Breiman</a> en el libro <span class="citation">(<a href="#ref-Breiman1984">Breiman et al. 1984</a>)</span> y son árboles de decisión que tienen como objetivo predecir la variable respuesta <span class="math inline">\(Y\)</span> en función de covariables.</p>
<div id="árboles-1" class="section level2 unnumbered hasAnchor">
<h2>Árboles<a href="arb-de-clasif.html#árboles-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación la imagen de un árbol común.</p>
<p align="center">
<img src="images/arbol.jpg" width="300">
</p>
<p>A continuación la imagen de un árbol seco e invertido.</p>
<p align="center">
<img src="images/dry_tree.png" width="300">
</p>
<p>Esta forma invertida es la forma de los árboles de regresión y clasificación.</p>
</div>
<div id="árbol-de-decisión-1" class="section level2 unnumbered hasAnchor">
<h2>Árbol de decisión<a href="arb-de-clasif.html#árbol-de-decisión-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Conjunto de reglas sucesivas que ayudan a tomar una decisión.</p>
<p align="center">
<img src="images/fit_unfit.png" width="500">
</p>
</div>
<div id="tipos-de-árboles-1" class="section level2 unnumbered hasAnchor">
<h2>Tipos de árboles<a href="arb-de-clasif.html#tipos-de-árboles-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los árboles se pueden clasificar en dos tipos que son:</p>
<ol style="list-style-type: decimal">
<li>Árboles de regresión en los cuales la variable respuesta <span class="math inline">\(y\)</span> es cuantitativa.</li>
<li>Árboles de clasificación en los cuales la variable respuesta <span class="math inline">\(y\)</span> es cualitativa.</li>
</ol>
<p align="center">
<img src="images/tipos_arboles.png" width="1000">
</p>
<p>El presente capítulo está destinado a árboles de clasificación, los árboles de regresión se explican en el capítulo <a href="arb-de-regre.html#arb-de-regre">1</a>.</p>
</div>
<div id="árbol-de-clasificación" class="section level2 unnumbered hasAnchor">
<h2>Árbol de clasificación<a href="arb-de-clasif.html#árbol-de-clasificación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Un árbol de regresión consiste en hacer preguntas del tipo ¿<span class="math inline">\(x_k \leq c\)</span>? para las covariables cuantitativas o preguntas del tipo ¿<span class="math inline">\(x_k = \text{nivel}_j\)</span>? para las covariables cualitativas, de esta forma el espacio de las covariables es divido en hiper-rectángulos y todas las observaciones que queden dentro de un hiper-rectángulo tendrán el mismo valor grupo estimado.</p>
<p>En la siguiente figura se ilustra el árbol en el lado izquierdo y la partición del espacio en el lado derecho. La partición del espacio se hace de manera repetitiva para encontrar las variables y los valores de corte <span class="math inline">\(c\)</span> de tal manera que se minimice la función de costos <span class="math inline">\(\sum_{i=1}^{i=n} (y_i - \hat{y}_i)^2\)</span>.</p>
<p><img src="libro_mod_pred_files/figure-html/nueva-1.png" width="672" /></p>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:randomForest&#39;:
## 
##     combine</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<p><img src="libro_mod_pred_files/figure-html/nueva-2.png" width="672" /></p>
<p align="center">
<img src="images/ilustracion_arb_clasi.png" width="800">
</p>
</div>
<div id="paquetes-de-r-para-construir-árboles" class="section level2 unnumbered hasAnchor">
<h2>Paquetes de R para construir árboles<a href="arb-de-clasif.html#paquetes-de-r-para-construir-árboles" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los paquetes más conocidos para construir árboles son:</p>
<ul>
<li><a href="https://cran.r-project.org/web/packages/tree/index.html">tree</a>.</li>
<li><a href="https://cran.r-project.org/web/packages/rpart/index.html">rpart</a>.</li>
<li><a href="https://cran.r-project.org/web/packages/party/index.html">party</a></li>
</ul>
<p>Existen otros paquetes que el lector puede consultar en la sección <em>Recursive Partitioning</em> de <a href="https://cran.r-project.org/web/views/MachineLearning.html">CRAN Task View: Machine Learning &amp; Statistical Learning</a>.</p>
</div>
<div id="ejemplo-con-rpart" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo con <strong>rpart</strong><a href="arb-de-clasif.html#ejemplo-con-rpart" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p align="center">
<img src="images/heart_attack.gif" width="200">
</p>
<p>La base de datos que vamos a usar en este ejemplo está disponible en el <a href="https://archive.ics.uci.edu/ml/datasets/Heart+Disease">UCI Repository</a>. El objetivo es crear un árbol de clasificación para predecir la variable <span class="math inline">\(Y\)</span> (<code>target</code>) definida como:</p>
<p><span class="math display">\[
Y=\left\{\begin{matrix}
1 \quad \text{si paciente SI sufre una enfermedad cardíaca} \\
0 \quad \text{si paciente NO sufre una enfermedad cardíaca}
\end{matrix}\right.
\]</span></p>
<p>en función de las variables <code>age</code> y <code>chol</code>.</p>
<p>Las variables en la base de datos son las siguientes:</p>
<ol style="list-style-type: decimal">
<li>Age: displays the age of the individual.</li>
<li>Sex: displays the gender of the individual using the following format: 1 = male, 0 = female.</li>
<li>Chest-pain type: displays the type of chest-pain experienced by the individual using the following format: 1 = typical angina, 2 = atypical angina, 3 = non — anginal pain, 4 = asymptotic.</li>
<li>Resting Blood Pressure: displays the resting blood pressure value of an individual in mmHg (unit)</li>
<li>Chol: displays the serum cholesterol in mg/dl (unit)</li>
<li>Fasting Blood Sugar: compares the fasting blood sugar value of an individual with 120mg/dl. If fasting blood sugar &gt; 120mg/dl then : 1 (true)
else : 0 (false).</li>
<li>Resting ECG : displays resting electrocardiographic results: 0 = normal
1 = having ST-T wave abnormality, 2 = left ventricular hyperthrophy.</li>
<li>Max heart rate achieved: displays the max heart rate achieved by an individual.</li>
<li>Exercise induced angina: 1 = yes, 0 = no.</li>
<li>ST depression induced by exercise relative to rest: displays the value which is an integer or float.</li>
<li>Peak exercise ST segment: 1 = upsloping, 2 = flat, 3 = downsloping.</li>
<li>Number of major vessels (0–3) colored by flourosopy : displays the value as integer or float.</li>
<li>Thal: displays the thalassemia: 3 = normal, 6 = fixed defect, 7 = reversible defect.</li>
<li>Target: Diagnosis of heart disease. Displays whether the individual is suffering from heart disease or not: 0 = absence, 1, 2, 3, 4 = present.</li>
</ol>
<p>La base de datos está en un repositorio en la web y se puede leer usando el siguiente código.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="arb-de-clasif.html#cb30-1" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb30-2"><a href="arb-de-clasif.html#cb30-2" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&#39;https://raw.githubusercontent.com/fhernanb/datos/master/cleveland.csv&#39;</span></span>
<span id="cb30-3"><a href="arb-de-clasif.html#cb30-3" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Como la base de datos viene sin los nombres se deben colocar manualmente así:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="arb-de-clasif.html#cb31-1" tabindex="-1"></a><span class="fu">colnames</span>(datos) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;age&#39;</span>, <span class="st">&#39;sex&#39;</span>, <span class="st">&#39;cp&#39;</span>, <span class="st">&#39;trestbps&#39;</span>, <span class="st">&#39;chol&#39;</span>,</span>
<span id="cb31-2"><a href="arb-de-clasif.html#cb31-2" tabindex="-1"></a>                     <span class="st">&#39;fbs&#39;</span>, <span class="st">&#39;restecg&#39;</span>, <span class="st">&#39;thalach&#39;</span>, <span class="st">&#39;exang&#39;</span>, </span>
<span id="cb31-3"><a href="arb-de-clasif.html#cb31-3" tabindex="-1"></a>                     <span class="st">&#39;oldpeak&#39;</span>, <span class="st">&#39;slope&#39;</span>, <span class="st">&#39;ca&#39;</span>, <span class="st">&#39;thal&#39;</span>, <span class="st">&#39;target&#39;</span>)</span></code></pre></div>
<p>La variable respuesta es <code>target</code> que tiene cuatro números así: 0 = absence, 1, 2, 3, 4 = present. Por esa razón vamos a crear la nueva variable <code>y</code> que agregaremos a la base de datos usando el siguiente código.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="arb-de-clasif.html#cb32-1" tabindex="-1"></a>datos<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(datos<span class="sc">$</span>target <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&#39;absence&#39;</span>, <span class="st">&#39;presence&#39;</span>)</span>
<span id="cb32-2"><a href="arb-de-clasif.html#cb32-2" tabindex="-1"></a>datos<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(datos<span class="sc">$</span>y)</span></code></pre></div>
<p>Nota: en orden lexicográfico la etiqueta <code>absence</code> está primero que <code>presence</code> porque inicia con la letra <code>a</code>. Eso significa que el árbol va a tomar la etiqueta <code>absence</code> como 0 mientras que <code>presence</code> la va a tomar como 1.</p>
<p>Nota: se pudo haber creado la variable <code>y</code> usando <code>ifelse(datos$target == 0, 0, 1)</code> pero decidimos usar los nombres <code>absence</code> y <code>presence</code> en lugar del 0 y 1 para facilitar su interpretación.</p>
<p>¿Cuántos pacientes hay en la base de datos?</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="arb-de-clasif.html#cb33-1" tabindex="-1"></a><span class="fu">nrow</span>(datos)</span></code></pre></div>
<pre><code>## [1] 303</code></pre>
<p>¿Cuántos pacientes presentan la enfermedad y cuántos no?</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="arb-de-clasif.html#cb35-1" tabindex="-1"></a><span class="fu">table</span>(datos<span class="sc">$</span>y)</span></code></pre></div>
<pre><code>## 
##  absence presence 
##      164      139</code></pre>
<p>Ahora vamos a crear un diagrama de dispersión de <code>chol</code> versus <code>age</code> diferenciando por <code>y</code> para observar si hay algún patrón claro a nuestros ojos.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="arb-de-clasif.html#cb37-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;ggplot2&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:randomForest&#39;:
## 
##     margin</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="arb-de-clasif.html#cb40-1" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>chol, <span class="at">col=</span>y)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="arb-de-clasif.html#cb40-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&#39;Edad&#39;</span>, <span class="at">y=</span><span class="st">&#39;Nivel colesterol&#39;</span>)</span></code></pre></div>
<p><img src="libro_mod_pred_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Para crear el árbol de clasificación usaremos la función <code>rpart</code> del paquete <strong>rpart</strong>. Para obtener más detalles de este paquete se recomienda consultar las viñetas del paquete disponibles <a href="https://cran.r-project.org/web/packages/rpart/index.html">en este enlace</a>.</p>
<p>El código para crear el árbol es el siguiente.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="arb-de-clasif.html#cb41-1" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb41-2"><a href="arb-de-clasif.html#cb41-2" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">rpart</span>(y <span class="sc">~</span> age <span class="sc">+</span> chol, <span class="at">data=</span>datos, <span class="at">method=</span><span class="st">&#39;class&#39;</span>)</span></code></pre></div>
<p>Para dibujar el árbol de clasificación podemos usar la función <code>rpart.plot</code> del paquete <strong>rpart.plot</strong>. Para obtener más detalles de este paquete se recomienda consultar la viñeta del paquete disponible <a href="http://www.milbo.org/doc/prp.pdf">en este enlace</a>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="arb-de-clasif.html#cb42-1" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb42-2"><a href="arb-de-clasif.html#cb42-2" tabindex="-1"></a><span class="fu">rpart.plot</span>(mod1, <span class="at">type=</span><span class="dv">0</span>, <span class="at">extra=</span><span class="dv">0</span>,  </span>
<span id="cb42-3"><a href="arb-de-clasif.html#cb42-3" tabindex="-1"></a>           <span class="at">box.palette =</span> <span class="fu">c</span>(<span class="st">&quot;lightgreen&quot;</span>, <span class="st">&quot;pink&quot;</span>))</span></code></pre></div>
<p><img src="libro_mod_pred_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Si nos cuesta trabajo entender el árbol anterior podemos generar las reglas de clasificación en un lenguaje sencillo así:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="arb-de-clasif.html#cb43-1" tabindex="-1"></a><span class="fu">rpart.rules</span>(mod1)</span></code></pre></div>
<pre><code>##     y                                          
##  0.26 when age &lt;  55       &amp; chol &lt;  274       
##  0.38 when age &gt;=       64 &amp; chol &gt;=        259
##  0.38 when age &lt;  55       &amp; chol &gt;=        287
##  0.45 when age &gt;=       64 &amp; chol &lt;  242       
##  0.65 when age is 55 to 64                     
##  0.86 when age &lt;  55       &amp; chol is 274 to 287
##  0.86 when age &gt;=       64 &amp; chol is 242 to 259</code></pre>
<ul>
<li>La primera línea de la salida anterior nos dice que “P(presence) = 0.26 para pacientes cuyo perfil es menor de 55 años y colesterol menor de 274”.</li>
<li>La última línea de la salida anterior nos dice que “P(presence) = 0.86 para pacientes cuyo perfil es mayor o igual a 64 años y colesterol entre 242 y 259”.</li>
</ul>
<p>Para construir la tabla de confusión usando los datos de entrenamiento podemos usar el siguiente código.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="arb-de-clasif.html#cb45-1" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">type=</span><span class="st">&#39;class&#39;</span>)</span>
<span id="cb45-2"><a href="arb-de-clasif.html#cb45-2" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Verdadero=</span>datos<span class="sc">$</span>y, <span class="at">Clasificacion=</span>y_hat)</span>
<span id="cb45-3"><a href="arb-de-clasif.html#cb45-3" tabindex="-1"></a>tabla</span></code></pre></div>
<pre><code>##           Clasificacion
## Verdadero  absence presence
##   absence      124       40
##   presence      56       83</code></pre>
<p>Para obtener la tasa de clasificación correcta podemos usar el siguiente código.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="arb-de-clasif.html#cb47-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">diag</span>(tabla)) <span class="sc">/</span> <span class="fu">sum</span>(tabla)</span></code></pre></div>
<pre><code>## [1] 0.6831683</code></pre>
<p>Supongamos que nos llegaron 3 pacientes, el primero un hombre de 45 años con nivel de colesterol 300, el segundo una mujer de 60 años con nivel de colesterol de 450 y el tercero otro hombre de 65 años con nivel de colesterol de 200. ¿A qué grupo se debe asignar cada paciente?</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="arb-de-clasif.html#cb49-1" tabindex="-1"></a>nuevo_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">60</span>, <span class="dv">65</span>),</span>
<span id="cb49-2"><a href="arb-de-clasif.html#cb49-2" tabindex="-1"></a>                       <span class="at">chol=</span><span class="fu">c</span>(<span class="dv">300</span>, <span class="dv">450</span>, <span class="dv">200</span>))</span>
<span id="cb49-3"><a href="arb-de-clasif.html#cb49-3" tabindex="-1"></a></span>
<span id="cb49-4"><a href="arb-de-clasif.html#cb49-4" tabindex="-1"></a><span class="fu">predict</span>(mod1, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&#39;prob&#39;</span>)</span></code></pre></div>
<pre><code>##     absence  presence
## 1 0.6190476 0.3809524
## 2 0.3486239 0.6513761
## 3 0.5500000 0.4500000</code></pre>
<p>Si queremos obtener las etiquetas de clasificación podemos usar:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="arb-de-clasif.html#cb51-1" tabindex="-1"></a><span class="fu">predict</span>(mod1, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&#39;class&#39;</span>)</span></code></pre></div>
<pre><code>##        1        2        3 
##  absence presence  absence 
## Levels: absence presence</code></pre>
<p>Supongamos que nos llegan 3 nuevos pacientes: el primero un hombre de 45 años pero no sabemos su nivel de colesterol, el segundo una mujer de edad desconocida y con nivel de colesterol de 450 y el tercero otro hombre del cual no sabemos ni su edad ni su nivel de colesterol. ¿A qué grupo se debe asignar cada paciente?</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="arb-de-clasif.html#cb53-1" tabindex="-1"></a>nuevo_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="fu">c</span>(<span class="dv">45</span>, <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb53-2"><a href="arb-de-clasif.html#cb53-2" tabindex="-1"></a>                       <span class="at">chol=</span><span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">450</span>, <span class="cn">NA</span>))</span>
<span id="cb53-3"><a href="arb-de-clasif.html#cb53-3" tabindex="-1"></a></span>
<span id="cb53-4"><a href="arb-de-clasif.html#cb53-4" tabindex="-1"></a><span class="fu">predict</span>(mod1, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&#39;prob&#39;</span>)</span></code></pre></div>
<pre><code>##     absence  presence
## 1 0.7391304 0.2608696
## 2 0.6250000 0.3750000
## 3 0.3486239 0.6513761</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="arb-de-clasif.html#cb55-1" tabindex="-1"></a><span class="fu">predict</span>(mod1, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&#39;class&#39;</span>)</span></code></pre></div>
<pre><code>##        1        2        3 
##  absence  absence presence 
## Levels: absence presence</code></pre>
</div>
<div id="ejemplo-con-tree" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo con <strong>tree</strong><a href="arb-de-clasif.html#ejemplo-con-tree" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vamos a construir un árbol de clasificación para los mismos datos del ejemplo anterior pero usando la función <code>tree</code> del paquete <code>tree</code>.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="arb-de-clasif.html#cb57-1" tabindex="-1"></a><span class="fu">library</span>(tree)</span>
<span id="cb57-2"><a href="arb-de-clasif.html#cb57-2" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">tree</span>(y <span class="sc">~</span> age <span class="sc">+</span> chol, <span class="at">data=</span>datos)</span></code></pre></div>
<p>Para dibujar el árbol.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="arb-de-clasif.html#cb58-1" tabindex="-1"></a><span class="fu">plot</span>(mod2, <span class="at">type=</span><span class="st">&#39;uniform&#39;</span>)</span>
<span id="cb58-2"><a href="arb-de-clasif.html#cb58-2" tabindex="-1"></a><span class="fu">text</span>(mod2)</span></code></pre></div>
<p><img src="libro_mod_pred_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Supongamos que nos llegaron 3 pacientes, el primero un hombre de 45 años con nivel de colesterol 300, el segundo una mujer de 60 años con nivel de colesterol de 450 y el tercero otro hombre de 65 años con nivel de colesterol de 200. ¿A qué grupo se debe asignar cada paciente?</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="arb-de-clasif.html#cb59-1" tabindex="-1"></a>nuevo_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">60</span>, <span class="dv">65</span>),</span>
<span id="cb59-2"><a href="arb-de-clasif.html#cb59-2" tabindex="-1"></a>                       <span class="at">chol=</span><span class="fu">c</span>(<span class="dv">300</span>, <span class="dv">450</span>, <span class="dv">200</span>))</span>
<span id="cb59-3"><a href="arb-de-clasif.html#cb59-3" tabindex="-1"></a></span>
<span id="cb59-4"><a href="arb-de-clasif.html#cb59-4" tabindex="-1"></a><span class="fu">predict</span>(mod2, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&#39;vector&#39;</span>)</span></code></pre></div>
<pre><code>##     absence  presence
## 1 0.5000000 0.5000000
## 2 0.7000000 0.3000000
## 3 0.4567901 0.5432099</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="arb-de-clasif.html#cb61-1" tabindex="-1"></a><span class="fu">predict</span>(mod2, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&#39;class&#39;</span>)</span></code></pre></div>
<pre><code>## [1] absence  absence  presence
## Levels: absence presence</code></pre>
</div>
<div id="ejemplo" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo<a href="arb-de-clasif.html#ejemplo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Comparemos los resultados obtenidos con las funciones <code>rpart</code> y <code>tree</code>.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="arb-de-clasif.html#cb63-1" tabindex="-1"></a>y_rpart <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">type=</span><span class="st">&#39;class&#39;</span>)</span>
<span id="cb63-2"><a href="arb-de-clasif.html#cb63-2" tabindex="-1"></a>y_tree  <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod2, <span class="at">type=</span><span class="st">&#39;class&#39;</span>)</span>
<span id="cb63-3"><a href="arb-de-clasif.html#cb63-3" tabindex="-1"></a></span>
<span id="cb63-4"><a href="arb-de-clasif.html#cb63-4" tabindex="-1"></a><span class="fu">table</span>(datos<span class="sc">$</span>y, y_rpart)</span></code></pre></div>
<pre><code>##           y_rpart
##            absence presence
##   absence      124       40
##   presence      56       83</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="arb-de-clasif.html#cb65-1" tabindex="-1"></a><span class="fu">table</span>(datos<span class="sc">$</span>y, y_tree)</span></code></pre></div>
<pre><code>##           y_tree
##            absence presence
##   absence      116       48
##   presence      45       94</code></pre>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Breiman1984" class="csl-entry">
Breiman, L., J. H. Friedman, R. A. Olshen, and C. J. Stone. 1984. <em>Classification and Regression Trees</em>. 1nd ed. Boca Raton, Florida: Chapman; Hall/CRC. <a href="https://www.crcpress.com/Classification-and-Regression-Trees/Breiman-Friedman-Stone-Olshen/p/book/9780412048418">https://www.crcpress.com/Classification-and-Regression-Trees/Breiman-Friedman-Stone-Olshen/p/book/9780412048418</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="arb-de-regre.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="arb-distri.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/libro_mod_pred/edit/master/1b-arb-clasi.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["libro_mod_pred.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
