<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Random Forests | Introducción a Machine Learning</title>
  <meta name="description" content="Libro de Modelos Predictivos" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Random Forests | Introducción a Machine Learning" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/cover2.png" />
  <meta property="og:description" content="Libro de Modelos Predictivos" />
  <meta name="github-repo" content="fhernanb/libro_mod_pred" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Random Forests | Introducción a Machine Learning" />
  
  <meta name="twitter:description" content="Libro de Modelos Predictivos" />
  <meta name="twitter:image" content="/images/cover2.png" />

<meta name="author" content="Freddy Hernández" />


<meta name="date" content="2026-05-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="arb-distri.html"/>
<link rel="next" href="svm-reg.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introducción a Machine Learning</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="knn-regre.html"><a href="knn-regre.html"><i class="fa fa-check"></i><b>1</b> k-NN para regresión</a>
<ul>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#paquetes-de-r-para-k-nn"><i class="fa fa-check"></i>Paquetes de R para k-NN</a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#paquete-fnn"><i class="fa fa-check"></i>Paquete <strong>FNN</strong></a>
<ul>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#m%C3%A9todo-brute-fuerza-bruta"><i class="fa fa-check"></i>Método <code>brute</code> (fuerza bruta)</a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#m%C3%A9todo-kd_tree-%C3%A1rbol-k-dimensional"><i class="fa fa-check"></i>Método <code>kd_tree</code> (árbol k-dimensional)</a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#m%C3%A9todo-cover_tree"><i class="fa fa-check"></i>Método <code>cover_tree</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#paquete-tidymodels"><i class="fa fa-check"></i>Paquete <strong>tidymodels</strong></a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#paquete-caret"><i class="fa fa-check"></i>Paquete <strong>caret</strong></a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#ejemplo-1-con-el-paquete-fnn"><i class="fa fa-check"></i>Ejemplo 1 con el paquete <strong>FNN</strong></a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#ejemplo-2-con-el-paquete-fnn"><i class="fa fa-check"></i>Ejemplo 2 con el paquete <strong>FNN</strong></a></li>
<li class="chapter" data-level="" data-path="knn-regre.html"><a href="knn-regre.html#ejemplo-con-el-paquete-tidymodels"><i class="fa fa-check"></i>Ejemplo con el paquete <strong>tidymodels</strong></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="regula.html"><a href="regula.html"><i class="fa fa-check"></i><b>2</b> Regularización</a>
<ul>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#regresi%C3%B3n-de-m%C3%ADnimos-cuadrados"><i class="fa fa-check"></i>Regresión de mínimos cuadrados</a></li>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#regresi%C3%B3n-ridge"><i class="fa fa-check"></i>Regresión Ridge</a>
<ul>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#ejemplo-de-regresi%C3%B3n-ridge"><i class="fa fa-check"></i>Ejemplo de regresión Ridge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#regresi%C3%B3n-lasso"><i class="fa fa-check"></i>Regresión Lasso</a>
<ul>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#ejemplo-de-regresi%C3%B3n-lasso"><i class="fa fa-check"></i>Ejemplo de regresión Lasso</a></li>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#conclusi%C3%B3n"><i class="fa fa-check"></i>Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#elastic-net"><i class="fa fa-check"></i>Elastic net</a>
<ul>
<li class="chapter" data-level="" data-path="regula.html"><a href="regula.html#ejemplo-de-elastic-net"><i class="fa fa-check"></i>Ejemplo de Elastic Net</a></li>
<li class="chapter" data-level="2.0.1" data-path="regula.html"><a href="regula.html#ridge-lasso-y-elastic-net"><i class="fa fa-check"></i><b>2.0.1</b> Ridge, Lasso y Elastic Net</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="arb-de-regre.html"><a href="arb-de-regre.html"><i class="fa fa-check"></i><b>3</b> Árboles de regresión</a>
<ul>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#%C3%A1rboles"><i class="fa fa-check"></i>Árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#%C3%A1rbol-de-decisi%C3%B3n"><i class="fa fa-check"></i>Árbol de decisión</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#tipos-de-%C3%A1rboles"><i class="fa fa-check"></i>Tipos de árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#%C3%A1rbol-de-regresi%C3%B3n"><i class="fa fa-check"></i>Árbol de regresión</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#paquetes-de-r-para-%C3%A1rboles"><i class="fa fa-check"></i>Paquetes de R para árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#paquete-rpart"><i class="fa fa-check"></i>Paquete <strong>rpart</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#paquete-tree"><i class="fa fa-check"></i>Paquete <strong>tree</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#ejemplo-con-el-paquete-rpart"><i class="fa fa-check"></i>Ejemplo con el paquete <strong>rpart</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-regre.html"><a href="arb-de-regre.html#ejemplo-con-el-paquete-tree"><i class="fa fa-check"></i>Ejemplo con el paquete <strong>tree</strong></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html"><i class="fa fa-check"></i><b>4</b> Árboles de clasificación</a>
<ul>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#%C3%A1rboles-1"><i class="fa fa-check"></i>Árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#%C3%A1rbol-de-decisi%C3%B3n-1"><i class="fa fa-check"></i>Árbol de decisión</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#tipos-de-%C3%A1rboles-1"><i class="fa fa-check"></i>Tipos de árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#%C3%A1rbol-de-clasificaci%C3%B3n"><i class="fa fa-check"></i>Árbol de clasificación</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#paquetes-de-r-para-construir-%C3%A1rboles"><i class="fa fa-check"></i>Paquetes de R para construir árboles</a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#ejemplo-con-rpart"><i class="fa fa-check"></i>Ejemplo con <strong>rpart</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#ejemplo-con-tree"><i class="fa fa-check"></i>Ejemplo con <strong>tree</strong></a></li>
<li class="chapter" data-level="" data-path="arb-de-clasif.html"><a href="arb-de-clasif.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="arb-distri.html"><a href="arb-distri.html"><i class="fa fa-check"></i><b>5</b> Árboles de regresión distribucionales</a>
<ul>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#videos-%C3%BAtiles"><i class="fa fa-check"></i>Videos útiles</a></li>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#paquete-disttree"><i class="fa fa-check"></i>Paquete disttree</a></li>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="arb-distri.html"><a href="arb-distri.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rand-forests.html"><a href="rand-forests.html"><i class="fa fa-check"></i><b>6</b> Random Forests</a>
<ul>
<li class="chapter" data-level="" data-path="rand-forests.html"><a href="rand-forests.html#explicaci%C3%B3n-sencilla-de-random-forests"><i class="fa fa-check"></i>Explicación sencilla de Random Forests</a></li>
<li class="chapter" data-level="" data-path="rand-forests.html"><a href="rand-forests.html#ejemplo-de-regresi%C3%B3n"><i class="fa fa-check"></i>Ejemplo de regresión</a></li>
<li class="chapter" data-level="" data-path="rand-forests.html"><a href="rand-forests.html#ejemplo-de-clasificaci%C3%B3n"><i class="fa fa-check"></i>Ejemplo de clasificación</a></li>
<li class="chapter" data-level="" data-path="rand-forests.html"><a href="rand-forests.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="rand-forests.html"><a href="rand-forests.html#random-forests-distribucionales"><i class="fa fa-check"></i>Random Forests distribucionales</a></li>
<li class="chapter" data-level="" data-path="rand-forests.html"><a href="rand-forests.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="svm-reg.html"><a href="svm-reg.html"><i class="fa fa-check"></i><b>7</b> Support Vector Machines para regresión</a>
<ul>
<li class="chapter" data-level="" data-path="svm-reg.html"><a href="svm-reg.html#paquetes-de-r-para-svm"><i class="fa fa-check"></i>Paquetes de R para svm</a></li>
<li class="chapter" data-level="" data-path="svm-reg.html"><a href="svm-reg.html#ventajas"><i class="fa fa-check"></i>Ventajas</a></li>
<li class="chapter" data-level="" data-path="svm-reg.html"><a href="svm-reg.html#ejemplos"><i class="fa fa-check"></i>Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="svm-clas.html"><a href="svm-clas.html"><i class="fa fa-check"></i><b>8</b> Support Vector Machines para clasificación</a>
<ul>
<li class="chapter" data-level="" data-path="svm-clas.html"><a href="svm-clas.html#paquetes-de-r-para-svm-1"><i class="fa fa-check"></i>Paquetes de R para svm</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="adaboost.html"><a href="adaboost.html"><i class="fa fa-check"></i><b>9</b> AdaBoost</a>
<ul>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#explicaci%C3%B3n-sencilla-de-adaboost"><i class="fa fa-check"></i>Explicación sencilla de AdaBoost</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#explicaci%C3%B3n-detallada-de-adaboost"><i class="fa fa-check"></i>Explicación detallada de AdaBoost</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#paquetes"><i class="fa fa-check"></i>Paquetes</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="adaboost.html"><a href="adaboost.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="adaboost_reg.html"><a href="adaboost_reg.html"><i class="fa fa-check"></i><b>10</b> AdaBoost</a></li>
<li class="chapter" data-level="11" data-path="gradboost.html"><a href="gradboost.html"><i class="fa fa-check"></i><b>11</b> Gradient Boost</a>
<ul>
<li class="chapter" data-level="" data-path="gradboost.html"><a href="gradboost.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="gradboost.html"><a href="gradboost.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="gradboost.html"><a href="gradboost.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html"><i class="fa fa-check"></i><b>12</b> Regresión lineal versus árboles de regresión</a>
<ul>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#regresi%C3%B3n-lineal"><i class="fa fa-check"></i>Regresión lineal</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#arboles-de-regresi%C3%B3n"><i class="fa fa-check"></i>Arboles de regresión</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#estudio-de-simulaci%C3%B3n-para-comparar-ambos-m%C3%A9todos"><i class="fa fa-check"></i>Estudio de simulación para comparar ambos métodos</a></li>
<li class="chapter" data-level="" data-path="reg-versus-arb.html"><a href="reg-versus-arb.html#retos"><i class="fa fa-check"></i>Retos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción a Machine Learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rand-forests" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Random Forests<a href="rand-forests.html#rand-forests" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Random Forest o Bosques Aleatorios fue propuesto por <span class="citation">Ho (<a href="#ref-Ho1995">1995</a>)</span> y consiste en crear muchos árboles para luego usarlos en la predicción de la variable de interés. A continuación se muestra una ilustración de la técnica.</p>
<p><a href="https://towardsdatascience.com/quick-intro-to-random-forest-3cb5006868d8"><img src="images/rand_forest_illustration.png" title="Ilustración de Random Forests" alt="Figura tomada de https://towardsdatascience.com/quick-intro-to-random-forest-3cb5006868d8" /></a></p>
<p>Abajo se presenta un video con una explicación detallada de cómo aplicar random forest para un caso sencillo de clasificación con <span class="math inline">\(n=4\)</span> observaciones y <span class="math inline">\(p=4\)</span> variables predictoras.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/J4Wdy0Wc_xQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<div id="explicación-sencilla-de-random-forests" class="section level2 unnumbered hasAnchor">
<h2>Explicación sencilla de Random Forests<a href="rand-forests.html#explicaci%C3%B3n-sencilla-de-random-forests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se inicia con un conjunto de entrenamiento que tiene <span class="math inline">\(n\)</span> observaciones, la variable interés <span class="math inline">\(Y\)</span> y las variables predictoras <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span>. Luego se aplican los siguientes pasos.</p>
<ol style="list-style-type: decimal">
<li>Se construye un nuevo conjunto de entrenamiento del mismo tamaño del original usando la técnica Bootstrap. Esto se hace generando un muestreo con reemplazo y de esta forma es posible que algunas observaciones aparezcan varias veces y mientras que otras observaciones no aparezcan.</li>
<li>Se construye un árbol (de regresión o clasificación) usando en cada partición un subconjunto con <span class="math inline">\(k\)</span> variables predictoras de las <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span> disponibles.</li>
<li>Se repiten los pasos anteriores <span class="math inline">\(B\)</span> veces, por lo general <span class="math inline">\(B=500\)</span> o <span class="math inline">\(B=1000\)</span>. De esta forma tendrám muchos árboles que luego se pueden usar para hacer predicciones de <span class="math inline">\(Y\)</span>.</li>
</ol>
<p>Si queremos predecir la variable <span class="math inline">\(Y\)</span> para un caso en el cual se tienen la información <span class="math inline">\((x_1, x_2, \ldots, x_p)^\top\)</span>, se toman cada uno de los <span class="math inline">\(B\)</span> árboles creados y se predice la variable <span class="math inline">\(Y\)</span>, de esta manera se trendrán las predicciones <span class="math inline">\(\hat{Y}_1, \hat{Y}_2, \ldots, \hat{Y}_B\)</span>. Luego usando estas <span class="math inline">\(B\)</span> predicciones, se puede obtener una predicción unificada dependiendo de si el problema es de clasificación o de regresión. A continuación una figura ilustrativa de cómo se unifican las <span class="math inline">\(B\)</span> predicciones.</p>
<p><a href="https://medium.com/swlh/random-forest-and-its-implementation-71824ced454f"><img src="images/rand_forest_clas_reg.png" title="Forma de unir las B predicciones" alt="Figura adaptada de https://medium.com/swlh/random-forest-and-its-implementation-71824ced454f" /></a></p>
</div>
<div id="ejemplo-de-regresión" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo de regresión<a href="rand-forests.html#ejemplo-de-regresi%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En este ejemplo vamos a usar los mismos datos de las casas en Boston para predecir la variable medv en función de diferentes características socioeconómicas, ambientales y estructurales de las viviendas. La base de datos <code>Boston</code> del paquete <code>MASS</code> de R contiene las variables crim (tasa de criminalidad per cápita por localidad), zn (proporción de terrenos residenciales destinados a lotes mayores de 25,000 pies cuadrados), indus (proporción de acres de negocios no minoristas por localidad), chas (variable indicadora del río Charles, donde 1 indica que la vivienda limita con el río y 0 en caso contrario), nox (concentración de óxidos nítricos en partes por 10 millones), rm (número promedio de habitaciones por vivienda), age (proporción de viviendas ocupadas por sus propietarios construidas antes de 1940), dis (distancia ponderada a cinco centros de empleo en Boston), rad (índice de accesibilidad a carreteras radiales), tax (tasa de impuesto a la propiedad por cada $10,000 del valor), ptratio (relación alumno-profesor en cada localidad), black (índice calculado como 1000(Bk − 0.63)^2, donde Bk representa la proporción de población afrodescendiente), lstat (porcentaje de la población de bajo estatus socioeconómico) y medv (valor mediano de las viviendas ocupadas por sus propietarios en miles de dólares) usando la base de datos Boston del paquete <strong>MASS</strong> de <span class="citation">Ripley and Venables (<a href="#ref-R-MASS">2025</a>)</span>.</p>
<p align="center">
<img src="images/Boston.jpeg" width="500">
</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="rand-forests.html#cb138-1" tabindex="-1"></a><span class="fu">library</span>(MASS)      <span class="co"># This package contains the dataset</span></span>
<span id="cb138-2"><a href="rand-forests.html#cb138-2" tabindex="-1"></a><span class="fu">head</span>(Boston)</span></code></pre></div>
<pre><code>##      crim zn indus chas   nox    rm  age    dis rad tax ptratio  black lstat
## 1 0.00632 18  2.31    0 0.538 6.575 65.2 4.0900   1 296    15.3 396.90  4.98
## 2 0.02731  0  7.07    0 0.469 6.421 78.9 4.9671   2 242    17.8 396.90  9.14
## 3 0.02729  0  7.07    0 0.469 7.185 61.1 4.9671   2 242    17.8 392.83  4.03
## 4 0.03237  0  2.18    0 0.458 6.998 45.8 6.0622   3 222    18.7 394.63  2.94
## 5 0.06905  0  2.18    0 0.458 7.147 54.2 6.0622   3 222    18.7 396.90  5.33
## 6 0.02985  0  2.18    0 0.458 6.430 58.7 6.0622   3 222    18.7 394.12  5.21
##   medv
## 1 24.0
## 2 21.6
## 3 34.7
## 4 33.4
## 5 36.2
## 6 28.7</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="rand-forests.html#cb140-1" tabindex="-1"></a><span class="fu">dim</span>(Boston)</span></code></pre></div>
<pre><code>## [1] 506  14</code></pre>
<p>Vamos a crear los datos de entrenamiento y de prueba usando la mitad de los datos, ya que tenemos en total 506 observaciones o registros. Para esto vamos a crear un vector con índices para identificar los elementos de entrenamiento <code>train_index</code>.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="rand-forests.html#cb142-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb142-2"><a href="rand-forests.html#cb142-2" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Boston), <span class="at">size =</span> <span class="dv">253</span>)</span>
<span id="cb142-3"><a href="rand-forests.html#cb142-3" tabindex="-1"></a>train_data  <span class="ot">&lt;-</span> Boston[train_index, ]</span>
<span id="cb142-4"><a href="rand-forests.html#cb142-4" tabindex="-1"></a>test_data   <span class="ot">&lt;-</span> Boston[<span class="sc">-</span>train_index, ]</span></code></pre></div>
<p>Para crear el modelo random forest se debe cargar la librería <em>randomForest</em> así:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="rand-forests.html#cb143-1" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code></pre></div>
<p>Vamos a crear un random forest con <span class="math inline">\(B=400\)</span> árboles y <span class="math inline">\(k=1\)</span> variables en cada partición, para esto podemos usar la siguiente instrucción:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="rand-forests.html#cb144-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb144-2"><a href="rand-forests.html#cb144-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(medv <span class="sc">~</span> ., <span class="at">data=</span>train_data, </span>
<span id="cb144-3"><a href="rand-forests.html#cb144-3" tabindex="-1"></a>                      <span class="at">ntree=</span><span class="dv">400</span>, <span class="at">mtry=</span><span class="dv">3</span>,</span>
<span id="cb144-4"><a href="rand-forests.html#cb144-4" tabindex="-1"></a>                      <span class="at">proximity=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>En el código anterior se fijó la semilla en el valor 12345 para que usted pueda replicar el ejemplo y obtener los mismos resultados.</p>
<p>Para explorar el modelo ajustado podemos hacer lo siguiente:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="rand-forests.html#cb145-1" tabindex="-1"></a>model</span></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = medv ~ ., data = train_data, ntree = 400,      mtry = 3, proximity = TRUE) 
##                Type of random forest: regression
##                      Number of trees: 400
## No. of variables tried at each split: 3
## 
##           Mean of squared residuals: 14.32854
##                     % Var explained: 82.32</code></pre>
<p>A continuación vamos a obtener medidas de desempeño para el modelo entrenado usand la base de datos de validación y el paquete <strong>yarrdstick</strong> de <span class="citation">Kuhn et al. (<a href="#ref-R-yardstick">2026</a>)</span>.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="rand-forests.html#cb147-1" tabindex="-1"></a><span class="fu">library</span>(yardstick)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;yardstick&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     rmse</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     spec</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="rand-forests.html#cb151-1" tabindex="-1"></a>predictions_rf <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> test_data, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb151-2"><a href="rand-forests.html#cb151-2" tabindex="-1"></a></span>
<span id="cb151-3"><a href="rand-forests.html#cb151-3" tabindex="-1"></a><span class="co"># Para calcular el MSE</span></span>
<span id="cb151-4"><a href="rand-forests.html#cb151-4" tabindex="-1"></a>mse_rf <span class="ot">&lt;-</span> <span class="fu">mse_vec</span>(<span class="at">truth=</span>test_data<span class="sc">$</span>medv, <span class="at">estimate=</span>predictions_rf)</span>
<span id="cb151-5"><a href="rand-forests.html#cb151-5" tabindex="-1"></a>mse_rf</span></code></pre></div>
<pre><code>## [1] 13.22873</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="rand-forests.html#cb153-1" tabindex="-1"></a><span class="co"># Para calcular el MAE</span></span>
<span id="cb153-2"><a href="rand-forests.html#cb153-2" tabindex="-1"></a>mae_rf <span class="ot">&lt;-</span> <span class="fu">mae_vec</span>(<span class="at">truth=</span>test_data<span class="sc">$</span>medv, <span class="at">estimate=</span>predictions_rf)</span>
<span id="cb153-3"><a href="rand-forests.html#cb153-3" tabindex="-1"></a>mae_rf</span></code></pre></div>
<pre><code>## [1] 2.452606</code></pre>
<p>Para tener una idea de la grandeza de los valores de MSE y MAE anteriores, vamos a ajustar dos modelos alternativos, un modelo regresión lineal simple y un árbol de regresión (sencillo).</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="rand-forests.html#cb155-1" tabindex="-1"></a><span class="co"># Ajustar modelo de regresión lineal simple</span></span>
<span id="cb155-2"><a href="rand-forests.html#cb155-2" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb155-3"><a href="rand-forests.html#cb155-3" tabindex="-1"></a></span>
<span id="cb155-4"><a href="rand-forests.html#cb155-4" tabindex="-1"></a><span class="co"># Ajustar árbol de regresión</span></span>
<span id="cb155-5"><a href="rand-forests.html#cb155-5" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb155-6"><a href="rand-forests.html#cb155-6" tabindex="-1"></a>model_tree <span class="ot">&lt;-</span> <span class="fu">rpart</span>(medv <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb155-7"><a href="rand-forests.html#cb155-7" tabindex="-1"></a></span>
<span id="cb155-8"><a href="rand-forests.html#cb155-8" tabindex="-1"></a><span class="co"># Predecir en el conjunto de prueba</span></span>
<span id="cb155-9"><a href="rand-forests.html#cb155-9" tabindex="-1"></a>predictions_lm <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lm, <span class="at">newdata =</span> test_data)</span>
<span id="cb155-10"><a href="rand-forests.html#cb155-10" tabindex="-1"></a>predictions_tree <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_tree, <span class="at">newdata =</span> test_data)</span>
<span id="cb155-11"><a href="rand-forests.html#cb155-11" tabindex="-1"></a></span>
<span id="cb155-12"><a href="rand-forests.html#cb155-12" tabindex="-1"></a><span class="co"># Calcular métricas de evaluación</span></span>
<span id="cb155-13"><a href="rand-forests.html#cb155-13" tabindex="-1"></a>mse_lm   <span class="ot">&lt;-</span> <span class="fu">mse_vec</span>(<span class="at">truth=</span>test_data<span class="sc">$</span>medv, <span class="at">estimate=</span>predictions_lm)</span>
<span id="cb155-14"><a href="rand-forests.html#cb155-14" tabindex="-1"></a>mse_tree <span class="ot">&lt;-</span> <span class="fu">mse_vec</span>(<span class="at">truth=</span>test_data<span class="sc">$</span>medv, <span class="at">estimate=</span>predictions_tree)</span>
<span id="cb155-15"><a href="rand-forests.html#cb155-15" tabindex="-1"></a></span>
<span id="cb155-16"><a href="rand-forests.html#cb155-16" tabindex="-1"></a>mae_lm   <span class="ot">&lt;-</span> <span class="fu">mae_vec</span>(<span class="at">truth=</span>test_data<span class="sc">$</span>medv, <span class="at">estimate=</span>predictions_lm)</span>
<span id="cb155-17"><a href="rand-forests.html#cb155-17" tabindex="-1"></a>mae_tree <span class="ot">&lt;-</span> <span class="fu">mae_vec</span>(<span class="at">truth=</span>test_data<span class="sc">$</span>medv, <span class="at">estimate=</span>predictions_tree)</span>
<span id="cb155-18"><a href="rand-forests.html#cb155-18" tabindex="-1"></a></span>
<span id="cb155-19"><a href="rand-forests.html#cb155-19" tabindex="-1"></a><span class="co"># Mostrar resultados</span></span>
<span id="cb155-20"><a href="rand-forests.html#cb155-20" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb155-21"><a href="rand-forests.html#cb155-21" tabindex="-1"></a>  <span class="at">Modelo =</span> <span class="fu">c</span>(<span class="st">&quot;Regresión Lineal&quot;</span>, <span class="st">&quot;Árbol de Regresión&quot;</span>, <span class="st">&quot;Random Forests&quot;</span>),</span>
<span id="cb155-22"><a href="rand-forests.html#cb155-22" tabindex="-1"></a>  <span class="at">MSE =</span> <span class="fu">c</span>(mse_lm, mse_tree, mse_rf),</span>
<span id="cb155-23"><a href="rand-forests.html#cb155-23" tabindex="-1"></a>  <span class="at">MAE =</span> <span class="fu">c</span>(mae_lm, mae_tree, mae_rf)</span>
<span id="cb155-24"><a href="rand-forests.html#cb155-24" tabindex="-1"></a>)</span>
<span id="cb155-25"><a href="rand-forests.html#cb155-25" tabindex="-1"></a><span class="fu">print</span>(results)</span></code></pre></div>
<pre><code>##               Modelo      MSE      MAE
## 1   Regresión Lineal 24.43010 3.513133
## 2 Árbol de Regresión 24.66654 3.374872
## 3     Random Forests 13.22873 2.452606</code></pre>
<p>De la salida anterior podemos ver que el modelo de random forest tiene mejores medidas de desempeño que los otros dos modelos de machine learning.</p>
</div>
<div id="ejemplo-de-clasificación" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo de clasificación<a href="rand-forests.html#ejemplo-de-clasificaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p align="center">
<img src="images/heart_attack.gif" width="200">
</p>
<p>La base de datos que vamos a usar en este ejemplo está disponible en el <a href="https://archive.ics.uci.edu/ml/datasets/Heart+Disease">UCI Repository</a>. El objetivo es crear un árbol de clasificación para predecir la variable <span class="math inline">\(Y\)</span> (<code>target</code>) definida como:</p>
<p><span class="math display">\[
Y=\left\{\begin{matrix}
1 \quad \text{si paciente SI sufre una enfermedad cardíaca} \\
0 \quad \text{si paciente NO sufre una enfermedad cardíaca}
\end{matrix}\right.
\]</span></p>
<p>en función de las variables <code>age</code> y <code>chol</code>.</p>
<p>Las variables en la base de datos son las siguientes:</p>
<ol style="list-style-type: decimal">
<li>Age: displays the age of the individual.</li>
<li>Sex: displays the gender of the individual using the following format: 1 = male, 0 = female.</li>
<li>Chest-pain type: displays the type of chest-pain experienced by the individual using the following format: 1 = typical angina, 2 = atypical angina, 3 = non — anginal pain, 4 = asymptotic.</li>
<li>Resting Blood Pressure: displays the resting blood pressure value of an individual in mmHg (unit)</li>
<li>Chol: displays the serum cholesterol in mg/dl (unit)</li>
<li>Fasting Blood Sugar: compares the fasting blood sugar value of an individual with 120mg/dl. If fasting blood sugar &gt; 120mg/dl then : 1 (true)
else : 0 (false).</li>
<li>Resting ECG : displays resting electrocardiographic results: 0 = normal
1 = having ST-T wave abnormality, 2 = left ventricular hyperthrophy.</li>
<li>Max heart rate achieved: displays the max heart rate achieved by an individual.</li>
<li>Exercise induced angina: 1 = yes, 0 = no.</li>
<li>ST depression induced by exercise relative to rest: displays the value which is an integer or float.</li>
<li>Peak exercise ST segment: 1 = upsloping, 2 = flat, 3 = downsloping.</li>
<li>Number of major vessels (0–3) colored by flourosopy : displays the value as integer or float.</li>
<li>Thal: displays the thalium scintigraphy: 3 = normal, 6 = fixed defect, 7 = reversible defect.</li>
<li>Target: Diagnosis of heart disease. Displays whether the individual is suffering from heart disease or not: 0 = absence, 1, 2, 3, 4 = present.</li>
</ol>
<p>La base de datos está en un repositorio en la web y se puede leer usando el siguiente código.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="rand-forests.html#cb157-1" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb157-2"><a href="rand-forests.html#cb157-2" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/fhernanb/datos/master/cleveland.csv&quot;</span></span>
<span id="cb157-3"><a href="rand-forests.html#cb157-3" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Como la base de datos viene sin los nombres se deben colocar manualmente así:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="rand-forests.html#cb158-1" tabindex="-1"></a><span class="fu">colnames</span>(datos) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;sex&quot;</span>, <span class="st">&quot;cp&quot;</span>, <span class="st">&quot;trestbps&quot;</span>, <span class="st">&quot;chol&quot;</span>,</span>
<span id="cb158-2"><a href="rand-forests.html#cb158-2" tabindex="-1"></a>                     <span class="st">&quot;fbs&quot;</span>, <span class="st">&quot;restecg&quot;</span>, <span class="st">&quot;thalach&quot;</span>, <span class="st">&quot;exang&quot;</span>, </span>
<span id="cb158-3"><a href="rand-forests.html#cb158-3" tabindex="-1"></a>                     <span class="st">&quot;oldpeak&quot;</span>, <span class="st">&quot;slope&quot;</span>, <span class="st">&quot;ca&quot;</span>, <span class="st">&quot;thal&quot;</span>, <span class="st">&quot;target&quot;</span>)</span></code></pre></div>
<p>La variable respuesta es <code>target</code> que tiene cuatro números así: 0 = absence, 1, 2, 3, 4 = present. Por esa razón vamos a crear la nueva variable <code>y</code> que agregaremos a la base de datos usando el siguiente código.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="rand-forests.html#cb159-1" tabindex="-1"></a>datos<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(datos<span class="sc">$</span>target <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;absence&quot;</span>, <span class="st">&quot;presence&quot;</span>)</span>
<span id="cb159-2"><a href="rand-forests.html#cb159-2" tabindex="-1"></a>datos<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(datos<span class="sc">$</span>y)</span></code></pre></div>
<p>Nota: en orden lexicográfico la etiqueta <code>absence</code> está primero que <code>presence</code> porque inicia con la letra <code>a</code>. Eso significa que el árbol va a tomar la etiqueta <code>absence</code> como 0 mientras que <code>presence</code> la va a tomar como 1.</p>
<p>Nota: se pudo haber creado la variable <code>y</code> usando <code>ifelse(datos$target == 0, 0, 1)</code> pero decidimos usar los nombres <code>absence</code> y <code>presence</code> en lugar del 0 y 1 para facilitar su interpretación.</p>
<p>Para crear el modelo random forest se debe cargar la librería <em>randomForest</em> así:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="rand-forests.html#cb160-1" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code></pre></div>
<p>Vamos a crear un random forest con <span class="math inline">\(B=400\)</span> árboles y <span class="math inline">\(k=1\)</span> variables en cada partición, para esto podemos usar la siguiente instrucción:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="rand-forests.html#cb161-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb161-2"><a href="rand-forests.html#cb161-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(y <span class="sc">~</span> age <span class="sc">+</span> chol, <span class="at">data=</span>datos, </span>
<span id="cb161-3"><a href="rand-forests.html#cb161-3" tabindex="-1"></a>                      <span class="at">ntree=</span><span class="dv">400</span>, <span class="at">mtry=</span><span class="dv">1</span>,</span>
<span id="cb161-4"><a href="rand-forests.html#cb161-4" tabindex="-1"></a>                      <span class="at">proximity=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>En el código anterior se fijó la semilla en el valor 12345 para que usted pueda replicar el ejemplo y obtener los mismos resultados.</p>
<p>Para explorar el modelo ajustado podemos hacer lo siguiente:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="rand-forests.html#cb162-1" tabindex="-1"></a>model</span></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = y ~ age + chol, data = datos, ntree = 400,      mtry = 1, proximity = TRUE) 
##                Type of random forest: classification
##                      Number of trees: 400
## No. of variables tried at each split: 1
## 
##         OOB estimate of  error rate: 45.54%
## Confusion matrix:
##          absence presence class.error
## absence       97       67   0.4085366
## presence      71       68   0.5107914</code></pre>
<p>De la salida anterior podemos destacar los siguientes resultados:</p>
<ul>
<li>El número de árboles utilizados fue de 400, valor que coincide con el indicado en la creación del modelo.</li>
<li>El número de variables usadas en cada partición de los árboles fue 1.</li>
<li>El error OOB (Out-Of-Bag) fue de 45.54%, error obtenido al clasificar las observaciones OOB que no fueron incluidas en el conjunto de datos de entrenamiento Boostrap.</li>
<li>La tasa de clasificación correcta de las observaciones OOB fue de 54.46%, y se obtiene del complemento del error OOB.</li>
<li>97 pacientes que NO sufren una enfermedad cardíaca, fueron clasificados correctamente en el grupo <strong>absence</strong>.</li>
<li>68 pacientes que SI sufren una enfermedad cardíaca, fueron clasificados correctamente en el grupo <strong>presence</strong>.</li>
<li>La tasa de clasificación correcta en este caso es
<span class="math display">\[
tcc = \frac{97+68}{97+67+71+68}=\frac{165}{303}=0.5445545 \approx 54\%
\]</span></li>
</ul>
<p>Supongamos que nos llegaron 3 pacientes, el primero un hombre de 45 años con nivel de colesterol 300, el segundo una mujer de 60 años con nivel de colesterol de 450 y el tercero otro hombre de 65 años con nivel de colesterol de 200. ¿A qué grupo se debe asignar cada paciente?</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="rand-forests.html#cb164-1" tabindex="-1"></a>nuevo_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">60</span>, <span class="dv">65</span>),</span>
<span id="cb164-2"><a href="rand-forests.html#cb164-2" tabindex="-1"></a>                       <span class="at">chol=</span><span class="fu">c</span>(<span class="dv">300</span>, <span class="dv">450</span>, <span class="dv">200</span>))</span>
<span id="cb164-3"><a href="rand-forests.html#cb164-3" tabindex="-1"></a></span>
<span id="cb164-4"><a href="rand-forests.html#cb164-4" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="at">newdata=</span>nuevo_df, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##       1       2       3 
## absence absence absence 
## Levels: absence presence</code></pre>
<p>De la salida anterior tenemos que los tres pacientes son clasificados en el grupo <strong>absence</strong>.</p>
</div>
<div id="ejemplo-3" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo<a href="rand-forests.html#ejemplo-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En el siguiente video se muestra como se puede crear un modelo random forest usando la totalidad de las variables de la base de datos del ejemplo anterior.</p>
<p>Mire el video y replique el ejemplo en su computador.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/6EXPYzbfLCE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
<div id="random-forests-distribucionales" class="section level2 unnumbered hasAnchor">
<h2>Random Forests distribucionales<a href="rand-forests.html#random-forests-distribucionales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>distree</strong> es un paquete de R propuesto por <span class="citation">Schlosser et al. (<a href="#ref-R-disttree">2025</a>)</span> para ajustar árboles y bosques de regresión distribucionales basado en la estimación de máxima verosimilitud de parámetros para familias de distribución específicas. Para instalar el paquete puedes usar el siguiente código.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="rand-forests.html#cb166-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;disttree&quot;</span>, <span class="at">repos=</span><span class="st">&quot;http://R-Forge.R-project.org&quot;</span>)</span></code></pre></div>
<p>Para crear un random forest (bosque aleatorio) distribucional se usa la función <code>distforest</code> que tiene la siguiente estructura.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="rand-forests.html#cb167-1" tabindex="-1"></a><span class="fu">distforest</span>(formula, data, subset, <span class="at">na.action =</span> na.pass, weights,</span>
<span id="cb167-2"><a href="rand-forests.html#cb167-2" tabindex="-1"></a>           offset, cluster, <span class="at">family =</span> <span class="fu">NO</span>(), strata, </span>
<span id="cb167-3"><a href="rand-forests.html#cb167-3" tabindex="-1"></a>           <span class="at">minsplit =</span> <span class="dv">20</span>, <span class="at">minbucket =</span> <span class="dv">7</span>, <span class="at">splittry =</span> <span class="dv">2</span></span>
<span id="cb167-4"><a href="rand-forests.html#cb167-4" tabindex="-1"></a>           <span class="at">control =</span> <span class="fu">disttree_control</span>(<span class="at">teststat =</span> <span class="st">&quot;quad&quot;</span>, <span class="at">testtype =</span> <span class="st">&quot;Univ&quot;</span>, ...)</span></code></pre></div>
<p>El argumento <code>family</code> se utiliza para indicar la distribución estadística que se asume para la variable respuesta <span class="math inline">\(Y\)</span>. Se puede elegir cualquier distribución de <strong>gamlss</strong> de <span class="citation">Stasinopoulos and Rigby (<a href="#ref-R-gamlss">2025</a>)</span> o cualquier distribución de los paquetes <strong>RelDists</strong> de <span class="citation">Hernandez-Barajas, Usuga, et al. (<a href="#ref-R-RelDists">2026</a>)</span>, <strong>RealDists</strong> de <span class="citation">(<a href="#ref-R-RealDists"><strong>R-RealDists?</strong></a>)</span> y <strong>DiscreteDists</strong> de <span class="citation">Hernandez-Barajas, Marmolejo-Ramos, et al. (<a href="#ref-R-DiscreteDists">2026</a>)</span>.</p>
</div>
<div id="ejemplo-4" class="section level2 unnumbered hasAnchor">
<h2>Ejemplo<a href="rand-forests.html#ejemplo-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Este ejemplo está basado en un ejemplo de <a href="https://www.zeileis.org/papers/Psychoco-2018.pdf">esta presentación</a> de Achim Zeileis. El modelo estadístico para simular los datos es el siguiente:</p>
<p align="center">
<img src="images/ecua_ejemplo_disttree.png" width="350">
</p>
<p>El siguiente código sirve para simular los datos.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="rand-forests.html#cb168-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb168-2"><a href="rand-forests.html#cb168-2" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb168-3"><a href="rand-forests.html#cb168-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>) </span>
<span id="cb168-4"><a href="rand-forests.html#cb168-4" tabindex="-1"></a>{</span>
<span id="cb168-5"><a href="rand-forests.html#cb168-5" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>n, <span class="at">min=</span><span class="sc">-</span><span class="fl">0.4</span>, <span class="at">max=</span><span class="dv">1</span>)</span>
<span id="cb168-6"><a href="rand-forests.html#cb168-6" tabindex="-1"></a>  media <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>(<span class="dv">4</span><span class="sc">*</span>x<span class="dv">-2</span>)<span class="sc">^</span>(<span class="dv">2</span><span class="sc">*</span>k))</span>
<span id="cb168-7"><a href="rand-forests.html#cb168-7" tabindex="-1"></a>  desvi <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">abs</span>(x)</span>
<span id="cb168-8"><a href="rand-forests.html#cb168-8" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>n, <span class="at">mean=</span>media, <span class="at">sd=</span>desvi)</span>
<span id="cb168-9"><a href="rand-forests.html#cb168-9" tabindex="-1"></a>}</span>
<span id="cb168-10"><a href="rand-forests.html#cb168-10" tabindex="-1"></a></span>
<span id="cb168-11"><a href="rand-forests.html#cb168-11" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(y, x)</span>
<span id="cb168-12"><a href="rand-forests.html#cb168-12" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code></pre></div>
<pre><code>##           y          x
## 1 8.7130091  0.6092655
## 2 4.7451104  0.8260825
## 3 8.3554765  0.6653753
## 4 1.0863330  0.8405744
## 5 2.3961818  0.2390733
## 6 0.2318576 -0.1670795</code></pre>
<p>Ahora vamos a explorar los datos simulados.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="rand-forests.html#cb170-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">19</span>)</span></code></pre></div>
<p><img src="libro_mod_pred_files/figure-html/rand-forest-1-1.png" alt="" width="672" /></p>
<p>El objetivo de este ejemplo es entrenar un árbol y un bosque distribucional para compararlos.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="rand-forests.html#cb171-1" tabindex="-1"></a><span class="fu">library</span>(disttree)</span>
<span id="cb171-2"><a href="rand-forests.html#cb171-2" tabindex="-1"></a></span>
<span id="cb171-3"><a href="rand-forests.html#cb171-3" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">disttree</span>(y <span class="sc">~</span> x, <span class="at">data=</span>datos, <span class="at">family=</span>NO)</span>
<span id="cb171-4"><a href="rand-forests.html#cb171-4" tabindex="-1"></a></span>
<span id="cb171-5"><a href="rand-forests.html#cb171-5" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">distforest</span>(y <span class="sc">~</span> x, <span class="at">data=</span>datos, <span class="at">family=</span>NO)</span></code></pre></div>
<p>Ahora vamos a crear un secuencia de datos para estimar <span class="math inline">\(Y\)</span> usando los dos modelos.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="rand-forests.html#cb172-1" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">seq</span>(<span class="at">from=</span><span class="sc">-</span><span class="fl">0.4</span>, <span class="at">to=</span><span class="dv">1</span>, <span class="at">length.out=</span><span class="dv">100</span>))</span></code></pre></div>
<p>Calculamos las estimaciones usando <code>predict</code>.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="rand-forests.html#cb173-1" tabindex="-1"></a>y_hat_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">newdata=</span>newdata)<span class="sc">$</span>mu <span class="co"># El resultado es mu y sigma</span></span>
<span id="cb173-2"><a href="rand-forests.html#cb173-2" tabindex="-1"></a>y_hat_2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod2, <span class="at">newdata=</span>newdata)<span class="sc">$</span>mu <span class="co"># elegimos solo mu</span></span></code></pre></div>
<p>Mostramos los resultados gráficamente.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="rand-forests.html#cb174-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">19</span>)</span>
<span id="cb174-2"><a href="rand-forests.html#cb174-2" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>newdata<span class="sc">$</span>x, <span class="at">y=</span>y_hat_1, <span class="at">col=</span><span class="st">&quot;tomato&quot;</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb174-3"><a href="rand-forests.html#cb174-3" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x=</span>newdata<span class="sc">$</span>x, <span class="at">y=</span>y_hat_2, <span class="at">col=</span><span class="st">&quot;chartreuse3&quot;</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb174-4"><a href="rand-forests.html#cb174-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;Arbol&quot;</span>, <span class="st">&quot;Bosque&quot;</span>),</span>
<span id="cb174-5"><a href="rand-forests.html#cb174-5" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;tomato&quot;</span>, <span class="st">&quot;chartreuse3&quot;</span>))</span></code></pre></div>
<p><img src="libro_mod_pred_files/figure-html/rand-forest-2-1.png" alt="" width="672" /></p>
<p>De la figura anterior podemos ver que la curva de estimación con bosques aleatorios es más flexible mientras que la del árbol no es nada flexible.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-R-DiscreteDists" class="csl-entry">
Hernandez-Barajas, Freddy, Fernando Marmolejo-Ramos, Olga Usuga-Manco, Jamiu Olumoh, and Osho Ajayi. 2026. <em>DiscreteDists: Discrete Statistical Distributions</em>. <a href="https://github.com/fhernanb/DiscreteDists">https://github.com/fhernanb/DiscreteDists</a>.
</div>
<div id="ref-R-RelDists" class="csl-entry">
Hernandez-Barajas, Freddy, Olga Usuga, Carmen Patino, and Jaime Mosquera. 2026. <em>RelDists: Estimation for Some Reliability Distributions</em>. <a href="https://fhernanb.github.io/RelDists/">https://fhernanb.github.io/RelDists/</a>.
</div>
<div id="ref-Ho1995" class="csl-entry">
Ho, Tin Kam. 1995. <span>“<span class="nocase">Random decision forests</span>.”</span> <em>Proceedings of the International Conference on Document Analysis and Recognition, ICDAR</em> 1. <a href="https://doi.org/10.1109/ICDAR.1995.598994">https://doi.org/10.1109/ICDAR.1995.598994</a>.
</div>
<div id="ref-R-yardstick" class="csl-entry">
Kuhn, Max, Davis Vaughan, and Emil Hvitfeldt. 2026. <em>Yardstick: Tidy Characterizations of Model Performance</em>. <a href="https://github.com/tidymodels/yardstick">https://github.com/tidymodels/yardstick</a>.
</div>
<div id="ref-R-MASS" class="csl-entry">
Ripley, Brian, and Bill Venables. 2025. <em>MASS: Support Functions and Datasets for Venables and Ripley’s MASS</em>. <a href="http://www.stats.ox.ac.uk/pub/MASS4/">http://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-disttree" class="csl-entry">
Schlosser, Lisa, Moritz N. Lang, Torsten Hothorn, and Achim Zeileis. 2025. <em>Disttree: Trees and Forests for Distributional Regression</em>. <a href="https://R-Forge.R-project.org/projects/partykit/">https://R-Forge.R-project.org/projects/partykit/</a>.
</div>
<div id="ref-R-gamlss" class="csl-entry">
Stasinopoulos, Mikis, and Robert Rigby. 2025. <em>Gamlss: Generalized Additive Models for Location Scale and Shape</em>. <a href="https://www.gamlss.com/">https://www.gamlss.com/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="arb-distri.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="svm-reg.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/fhernanb/libro_mod_pred/edit/master/2-random_forests.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["libro_mod_pred.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
